version: '3.2'
services:
    nginx:
        image: nginx:1.19-alpine
        hostname: nginx-reverse
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - backend
   
    db-redis:
        image: myredis
        build: .
        restart: unless-stopped
        ports:
            - 6379:6379
        hostname: redis
        container_name: db-redis
        command: redis-server
        
        
    backend:
        image: be2
        hostname: be2
        build: .
        container_name: backend2
        ports: 
            - 8080:8080
        environment:
            - PORT=8080
            - REQUEST_ORIGIN=http://localhost
            - REDIS_HOST=redis   
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=postgres
        depends_on:
            - db-postgres
            - db-redis
        
    frontend:
        image: fe2
        hostname: fe2
        container_name: frontend2
        build: .
        ports:
            - 5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost/api
            
    db-postgres:
        image: postgres:14-alpine
        container_name: db-postgres
        restart: unless-stopped
        hostname: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user       
        volumes:
            - ./database:/var/lib/postgresql/data
           