version: "3"
services:
    pipeline-test:
        image: lilililim/pipeline-test
        ports:
        - 4000:80
        container_name: pipeline-test
    watchtower:
        image: containrrr/watchtower
        environment:
        -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower