version: '3.5'

services:
    db:
        image: myredis
        build: .
        restart: unless-stopped
        ports:
            - 6379:6379
        hostname: redis
        command: redis-server
        
        
    backend:
        image: be2
        build: .
        ports: 
            - 8080:8080
        environment:
            - PORT=8080
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis        
        
    frontend:
        image: fe2
        build: .
        ports:
            - 5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
            