version: '3'

services:
    up:
        image: devopsdockeruh/simple-web-service
        build: .        
        volumes:
            - ./text.log:/usr/src/app/text.log
        container_name: es-2-1