version: '3.5'

services:
    db-redis:
        image: myredis
        build: .
        restart: unless-stopped
        ports:
            - 6379:6379
        hostname: redis
        container_name: db-redis
        command: redis-server
        
        
    backend:
        image: be2
        build: .
        container_name: backend2
        ports: 
            - 8080:8080
        environment:
            - PORT=8080
            - REQUEST_ORIGIN=http://localhost:5000
            - REDIS_HOST=redis   
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DATABASE=postgres
        depends_on:
            - db-postgres
            - db-redis
        
    frontend:
        image: fe2
        container_name: frontend2
        build: .
        ports:
            - 5000:5000
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:8080
            
    db-postgres:
        image: postgres:14-alpine
        container_name: db-postgres
        restart: unless-stopped
        hostname: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user       
        volumes:
            - db-postgres-volume:/var/lib/postgresql/data
            
volumes:
    db-postgres-volume: 
            